#!/usr/bin/env python3
"""CLI entry point generated by new_cliche."""


def main():
    from new_cliche.runtime import run_package_cli
    run_package_cli("sysdm")


if __name__ == "__main__":
    main()
